import { QueryInterface } from "sequelize";

export default {
    async up(queryInterface: QueryInterface) {
        await queryInterface.bulkInsert('users', [
            {
                nip: 12345678,
                firstName: 'Helber',
                lastName: 'Brito',
                department: 'Administrativo',
                section: true,
                division: false,
                role: 'admin',
                status: true,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: 20240011,
                firstName: 'Sandro',
                lastName: 'CMG',
                department: 'Informática',
                section: true,
                division: false,
                role: 'admin',
                status: true,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: 20240012,
                firstName: 'Luana',
                lastName: 'TEN',
                department: 'Informática',
                section: true,
                division: false,
                role: 'admin',
                status: true,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: 20240013,
                firstName: 'Oriel',
                lastName: 'SGT',
                department: 'Informática',
                section: true,
                division: false,
                role: 'admin',
                status: true,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: 20240014,
                firstName: 'Brito',
                lastName: 'MAR',
                department: 'Informática',
                section: true,
                division: false,
                role: 'admin',
                status: true,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: 20240015,
                firstName: 'Dos Anjos',
                lastName: 'CB',
                department: 'Informática',
                section: true,
                division: false,
                role: 'admin',
                status: true,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: 20240016,
                firstName: 'Cavalcante',
                lastName: 'CB',
                department: 'Informática',
                section: true,
                division: false,
                role: 'admin',
                status: true,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: 20240017,
                firstName: 'Lucas',
                lastName: '4D',
                department: 'Suporte',
                section: false,
                division: true,
                role: 'user',
                status: false,
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
        ])
    },

    async down(queryInterface: QueryInterface) {
        await queryInterface.bulkDelete('users', null, {})
    }
}
