import { QueryInterface } from "sequelize";

export default {
    async up(queryInterface: QueryInterface) {
        await queryInterface.bulkInsert('users', [
            {
                nip: '12345678',
                idPatent: 1,
                warName: 'HB',
                firstName: 'Helber',
                lastName: 'Brito',
                role: 'admin',
                status: "true",
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: '22345678',
                idPatent: 1,
                warName: 'Brito',
                firstName: 'Helber',
                lastName: 'Brito',
                role: 'admin',
                status: "true",
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: '20240011',
                idPatent: 2,
                warName: 'Comandante',
                firstName: 'Sandro',
                lastName: 'Marinha',
                role: 'admin',
                status: "true",
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: '20240012',
                idPatent: 2,
                warName: 'Tenente',
                firstName: 'Luana',
                lastName: 'Vianna',
                role: 'admin',
                status: "true",
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                nip: '20240013',
                idPatent: 2,
                warName: 'Sargento',
                firstName: 'Oriel',
                lastName: 'Marinha',
                role: 'admin',
                status: "true",
                permission: 'rwe',
                password: '@Mb2024',
                emailPersonal: 'email@email.com',
                emailMb: 'email@mb.mil.br',
                contactNumber: 6199887766,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            // {
            //     nip: '20240014',
            //     patent: 'MAR',
            //     warName: 'Brito',
            //     firstName: 'Brito',
            //     lastName: 'Marinha',
            //     department: 'Informática',
            //     section: true,
            //     division: false,
            //     role: 'admin',
            //     status: "true",
            //     permission: 'rwe',
            //     password: '@Mb2024',
            //     emailPersonal: 'email@email.com',
            //     emailMb: 'email@mb.mil.br',
            //     contactNumber: 6199887766,
            //     createdAt: new Date(),
            //     updatedAt: new Date()
            // },
            // {
            //     nip: '20240015',
            //     patent: 'CB',
            //     warName: 'Dos Anjos',
            //     firstName: 'Dos Anjos',
            //     lastName: 'Marinha',
            //     department: 'Informática',
            //     section: true,
            //     division: false,
            //     role: 'admin',
            //     status: "true",
            //     permission: 'rwe',
            //     password: '@Mb2024',
            //     emailPersonal: 'email@email.com',
            //     emailMb: 'email@mb.mil.br',
            //     contactNumber: 6199887766,
            //     createdAt: new Date(),
            //     updatedAt: new Date()
            // },
            // {
            //     nip: '20240016',
            //     patent: 'CB',
            //     warName: 'Cavalcante',
            //     firstName: 'Cavalcante',
            //     lastName: 'Marinha',
            //     department: 'Informática',
            //     section: true,
            //     division: false,
            //     role: 'admin',
            //     status: "true",
            //     permission: 'rwe',
            //     password: '@Mb2024',
            //     emailPersonal: 'email@email.com',
            //     emailMb: 'email@mb.mil.br',
            //     contactNumber: 6199887766,
            //     createdAt: new Date(),
            //     updatedAt: new Date()
            // },
            // {
            //     nip: '20240017',
            //     patent: 'Civil',
            //     warName: '4D',
            //     firstName: 'Lucas',
            //     lastName: '4D',
            //     department: 'Suporte',
            //     section: false,
            //     division: true,
            //     role: 'user',
            //     status: false,
            //     permission: 'rwe',
            //     password: '@Mb2024',
            //     emailPersonal: 'email@email.com',
            //     emailMb: 'email@mb.mil.br',
            //     contactNumber: 6199887766,
            //     createdAt: new Date(),
            //     updatedAt: new Date()
            // },
        ])
    },

    async down(queryInterface: QueryInterface) {
        await queryInterface.bulkDelete('users', null, {})
    }
}
