import { QueryInterface } from "sequelize";

export default {
    async up(queryInterface: QueryInterface) {
        await queryInterface.bulkInsert('TABLE_SCHEDULING', [
            // IRÃO ACONTECER
            // AUDITORIO - mes=mes; dia=dia
            {
                nip: '12345678',
                schedulingStart: new Date('2025-04-20T09:00:00.000Z'),
                schedulingEnd: new Date('2025-04-20T10:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Workshop de Introdução ao React',
                description: 'Um workshop prático para iniciantes em React.',
                typeScheduling: 'auditorium',
                ramal: '0001',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-04-20T10:30:00.000Z'),
                schedulingEnd: new Date('2025-04-20T11:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Workshop de Introdução ao JavaScript',
                description: 'Um workshop prático para iniciantes em Javascript.',
                typeScheduling: 'auditorium',
                ramal: '0001',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-04-20T11:30:00.000Z'),
                schedulingEnd: new Date('2025-04-20T13:00:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Gestão de chaves Orion',
                description: 'Explicação de como gerenciar chaves Orion.',
                typeScheduling: 'auditorium',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            // AUDITORIO - mes=mes; dia != dia
            {
                nip: '11223344',
                schedulingStart: new Date('2025-03-19T08:30:00.000Z'),
                schedulingEnd: new Date('2025-03-19T09:45:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Como malhar pra ficar fortão',
                description: 'Demostração de exercícios de alta performance para ser um marinheiro alto padrão, forte e humilde.',
                typeScheduling: 'auditorium',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-03-21T14:00:00.000Z'),
                schedulingEnd: new Date('2025-03-21T16:15:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Jogos online - do 0 ao profissional em 3 dias',
                description: 'Evento totalmente online e totalmente gratuito para se tornar um jogador profisisonal de e-sports.',
                typeScheduling: 'auditorium',
                ramal: '0002',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-03-22T08:30:00.000Z'),
                schedulingEnd: new Date('2025-03-22T10:45:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Natação de alta performance',
                description: 'O segredo para nadar em linha reta como um torpedo.',
                typeScheduling: 'auditorium',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            // AUDITORIO - mes!=mes; dia=dia
            {
                nip: '11223344',
                schedulingStart: new Date('2025-05-01T08:10:00.000Z'),
                schedulingEnd: new Date('2025-05-01T09:50:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Como malhar pra ficar fortão',
                description: 'Demostração de exercícios de alta performance para ser um marinheiro alto padrão, forte e humilde.',
                typeScheduling: 'auditorium',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-06-01T14:00:00.000Z'),
                schedulingEnd: new Date('2025-06-01T16:15:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Jogos online - do 0 ao profissional em 3 dias',
                description: 'Evento totalmente online e totalmente gratuito para se tornar um jogador profisisonal de e-sports.',
                typeScheduling: 'auditorium',
                ramal: '0002',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-07-01T08:30:00.000Z'),
                schedulingEnd: new Date('2025-07-01T10:45:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Natação de alta performance',
                description: 'O segredo para nadar em linha reta como um torpedo.',
                typeScheduling: 'auditorium',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            // JÁ ACONTECERAM
            {
                nip: '12345678',
                schedulingStart: new Date('2025-01-20T09:00:00.000Z'),
                schedulingEnd: new Date('2025-01-20T10:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Já se foi o disco voador',
                description: 'Episódio marcante do seu Barriga.',
                typeScheduling: 'auditorium',
                ramal: '0001',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-01-20T10:30:00.000Z'),
                schedulingEnd: new Date('2025-01-20T11:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Pepe, já tirei a vela!',
                description: 'Um clássico do chapolim.',
                typeScheduling: 'auditorium',
                ramal: '0001',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-01-20T11:30:00.000Z'),
                schedulingEnd: new Date('2025-01-20T13:00:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Venha tesouro, não se junte com a gentalha.',
                description: 'O inexorável Kiko.',
                typeScheduling: 'auditorium',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            // IRÃO ACONTECER
            // SALA DE REUNIÕES - mes=mes; dia=dia
            {
                nip: '12345678',
                schedulingStart: new Date('2025-04-20T09:00:00.000Z'),
                schedulingEnd: new Date('2025-04-20T10:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Workshop de Introdução ao React',
                description: 'Um workshop prático para iniciantes em React.',
                typeScheduling: 'meeting-room',
                ramal: '0001',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-04-20T10:30:00.000Z'),
                schedulingEnd: new Date('2025-04-20T11:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Workshop de Introdução ao JavaScript',
                description: 'Um workshop prático para iniciantes em Javascript.',
                typeScheduling: 'meeting-room',
                ramal: '0001',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-04-20T11:30:00.000Z'),
                schedulingEnd: new Date('2025-04-20T13:00:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Gestão de chaves Orion',
                description: 'Explicação de como gerenciar chaves Orion.',
                typeScheduling: 'meeting-room',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            // SALA DE REUNIÕES - mes=mes; dia != dia
            {
                nip: '11223344',
                schedulingStart: new Date('2025-03-19T08:30:00.000Z'),
                schedulingEnd: new Date('2025-03-19T09:45:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Como malhar pra ficar fortão',
                description: 'Demostração de exercícios de alta performance para ser um marinheiro alto padrão, forte e humilde.',
                typeScheduling: 'meeting-room',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-03-21T14:00:00.000Z'),
                schedulingEnd: new Date('2025-03-21T16:15:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Jogos online - do 0 ao profissional em 3 dias',
                description: 'Evento totalmente online e totalmente gratuito para se tornar um jogador profisisonal de e-sports.',
                typeScheduling: 'meeting-room',
                ramal: '0002',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-03-22T08:30:00.000Z'),
                schedulingEnd: new Date('2025-03-22T10:45:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Natação de alta performance',
                description: 'O segredo para nadar em linha reta como um torpedo.',
                typeScheduling: 'meeting-room',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            // SALA DE REUNIÕES - mes!=mes; dia=dia
            {
                nip: '11223344',
                schedulingStart: new Date('2025-05-01T08:10:00.000Z'),
                schedulingEnd: new Date('2025-05-01T09:50:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Como malhar pra ficar fortão',
                description: 'Demostração de exercícios de alta performance para ser um marinheiro alto padrão, forte e humilde.',
                typeScheduling: 'meeting-room',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-06-01T14:00:00.000Z'),
                schedulingEnd: new Date('2025-06-01T16:15:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Jogos online - do 0 ao profissional em 3 dias',
                description: 'Evento totalmente online e totalmente gratuito para se tornar um jogador profisisonal de e-sports.',
                typeScheduling: 'meeting-room',
                ramal: '0002',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-07-01T08:30:00.000Z'),
                schedulingEnd: new Date('2025-07-01T10:45:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Natação de alta performance',
                description: 'O segredo para nadar em linha reta como um torpedo.',
                typeScheduling: 'meeting-room',
                ramal: '7376',
                status: true,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            // SALA DE REUNIÕES - JÁ ACONTECERAM
            {
                nip: '12345678',
                schedulingStart: new Date('2025-01-20T09:00:00.000Z'),
                schedulingEnd: new Date('2025-01-20T10:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Já se foi o disco voador',
                description: 'Episódio marcante do seu Barriga.',
                typeScheduling: 'meeting-room',
                ramal: '0001',
                status: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '12345678',
                schedulingStart: new Date('2025-01-20T10:30:00.000Z'),
                schedulingEnd: new Date('2025-01-20T11:00:00.000Z'),
                nameResponsible: 'Helber',
                theme: 'Pepe, já tirei a vela!',
                description: 'Um clássico do chapolim.',
                typeScheduling: 'meeting-room',
                ramal: '0001',
                status: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                nip: '11223344',
                schedulingStart: new Date('2025-01-20T11:30:00.000Z'),
                schedulingEnd: new Date('2025-01-20T13:00:00.000Z'),
                nameResponsible: 'Cavalcante',
                theme: 'Venha tesouro, não se junte com a gentalha.',
                description: 'O inexorável Kiko.',
                typeScheduling: 'meeting-room',
                ramal: '7376',
                status: false,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ])
    },

    async down(queryInterface: QueryInterface) {
        await queryInterface.bulkDelete('TABLE_SCHEDULING', null, {})
    }
}
